version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /src/main/frontend
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /src/main/desktop
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /src/main/docker/liquibase
    schedule:
      interval: monthly
