apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kitezh.fullname" . }}
  labels:
    {{ include "kitezh.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      profiles:
        active: {{ .Values.spring.profiles.active | quote }}
      liquibase:
        enabled: {{ .Values.spring.liquibase.enabled }}
      datasource:
        url: {{ .Values.spring.datasource.url | quote }}
    app:
      authorization-server:
        issuer: {{ .Values.app.authorizationServer.issuer | quote }}
        offline-session-idle: {{ .Values.app.authorizationServer.offlineSessionIdle | quote }}
